### ISSUE TITLE
Delete volunteer option in volunteer list page doesn't work as expected

### ISSUE THREAD

**Issue by stavlocker** [itay-sho/LevEchad#102]
It seems like the deletion option in the volunteer table page only deletes the volunteer badge, and not the user. Either:
 * This is intended: Make it clear that the deletion relates to the badge and not the user (frontend fix)
 * This is unintended:  Make it delete the user (backend fix)

**Comment by stavlocker** [comment]
@itay-sho Is this behaviour intended or not? If you don't know please @ someone who will

**Comment by astar26** [comment]
As the last person to edit this piece of code (and since it predates the badges), I don't see the issue. care to explain a bit more?

`@login_required
def delete_volunteer(request, pk):
    to_delete = Volunteer.objects.get(id=pk)
    to_delete.delete()
    return redirect('show_all_volunteers')`

**Comment by stavlocker** [comment]
I can't reproduce this in the latest develop.
