### ISSUE TITLE
Use JS datepicker

### ISSUE THREAD

**Issue by itay-sho** [itay-sho/LevEchad#105]
Replace this:
![image](https://user-images.githubusercontent.com/5647956/77861072-80465d80-721b-11ea-8cbc-448883c285c1.png)

Without something like this:
![image](https://user-images.githubusercontent.com/5647956/77861080-8ccab600-721b-11ea-8bfe-39933edd1f07.png)

**Comment by astar26** [comment]
Still work to be done, ETA Tomorrow

**Comment by astar26** [comment]
Didn't we close this? @itay-sho

**Comment by stavlocker** [comment]
I'm closing this issue as it's already been merged, re-open if necessary.
