### ISSUE TITLE
change to a smaller favicon

### ISSUE THREAD

**Issue by itay-sho** [itay-sho/LevEchad#118]
currently, the icon isn't looking so good
![image](https://user-images.githubusercontent.com/5647956/77927478-f1375500-72af-11ea-9a62-fad2ebdf3988.png)

**Comment by itay-sho** [comment]
after the update it looks like that:
![image](https://user-images.githubusercontent.com/5647956/77927615-19bf4f00-72b0-11ea-8d0c-bc6f7e948d18.png)

creating a pull request now...

**Comment by stavlocker** [comment]
Seems like this was merged and can be closed :)

**Comment by stavlocker** [comment]
Merged in #119, closing issue (re-open if necessary)
