### ISSUE TITLE
Make volunteer badges cache themselves instead of redrawing on request

### ISSUE THREAD

**Issue by stavlocker** [itay-sho/LevEchad#121]
Currently every time you request a volunteer badge, it draws the template and then serves the drawn image to the user. This happens every time someone queries the badge, making it inefficient.
This is especially crucial now that we want to reduce CPU consumption!

Make the images cache themselves as static files which will be served and add hooks to field changes to redraw & resave the image if necessary.

**Comment by astar26** [comment]
Pay attention to cleanup - no need to keep expired certificates.
