### ISSUE TITLE
Merge volunteer_pager and request_pager into one snippet

### ISSUE THREAD

**Issue by itay-sho** [itay-sho/LevEchad#148]
_Originally posted by @astar26 in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjQ4NzU5NzAwOnYy/pull_request_review_threads/discussion_

**Comment by stavlocker** [comment]
This might not be relevant, as part of the new REST API a new filtering system will be written.

Closing this, @astar26 if you still want this issue to be done then reopen (and correct me)
