### ISSUE TITLE
Refactor GET parameters in volunteer and request view filtering

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#153]
No need to use getlist for everything, also later checks need to be refactored.

**Comment by itay-sho** [comment]
Can you mention where exactly is it?

**Comment by astar26** [comment]
Server/views.py:
- show_all_volunteers
- show_all_help_request

**Comment by stavlocker** [comment]
This might not be relevant, as part of the new REST API a new filtering system will be written.

Closing this, @astar26 if you still want this issue to be done then reopen (and correct me)
