### ISSUE TITLE
Use OpenStreetMap to autocomplete all streets in a city (frontend side)

### ISSUE THREAD

**Issue by stavlocker** [itay-sho/LevEchad#188]
OpenStreetMap has a feature to query street names in a city, we can use this to have autocompleted streets on the frontend side once they type in a city (and we'd probably want autocomplete for a city too).

They have a pretty comprehensive query language so this could require a bit of digging into it.

**Comment by astar26** [comment]
From a [sample](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#List_of_streets):
`[out:csv("name";false)];
area[name="Troisdorf"];
way(area)[highway][name];
out;`
Note - read about the protocol and endpoints: [OverpassAPI](https://wiki.openstreetmap.org/wiki/Overpass_API)

**Comment by stavlocker** [comment]
Moved to [levechad-frontend#1](https://github.com/Lev-Echad/levechad-frontend/issues/1)
