### ISSUE TITLE
Update volunteer registration data

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#26]
Change: 
-Instead of full name, have separate first and last name fields.
Add:
-Organization (not required)
-Volunteer Type: משימות, משפחתון, פרויקט, חמ"ל, מטה,רכז עיר,רכז שכונה (default: משימות, changed by hamal)
-Neighbourhood (not required)

**Comment by flight-alert** [comment]
Work on this issue has been completed.
