### ISSUE TITLE
Add sorting of nearby volunteers view by ammount of requests taken

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#48]
To allow differentiation in task-assignment.

**Comment by astar26** [comment]
Relevant to the closest volunteers view

**Comment by stavlocker** [comment]
Could you clarify what you mean by sorting the volunteers view by amount of requests?

**Comment by astar26** [comment]
> 
> 
> Could you clarify what you mean by sorting the volunteers view by amount of requests?

This issue requires a full refactor of the view, as it is extremely inefficient, and sorts twice, instead of sorting by two keys (which obviously discards the first sort).

The view has a calculated field for ammount of requests taken by volunteer. Moving this calculation to the DB would be the way to go, as it is much more CPU and memory efficient.
