### ISSUE TITLE
Fix phone number verification

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#49]
Can't give 077 prefix (HOT)

**Comment by yoavmag** [comment]
I can't reproduce it. I think its already resolved

**Comment by stavlocker** [comment]
Can also confirm - tried this in development with the latest develop and it seems to work.
Close this issue?

**Comment by stavlocker** [comment]
Okay, I see - this refers to the BaseHelpForm and not the VolunteerForm.

I opened issue #117 which covers this subject within it, so it's safe to close this one as the problem here is bigger (As described in the issue I opened).
