### ISSUE TITLE
Add view to edit volunteers

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#86]
Important fields: ID number, volunteer type, address

**Comment by flight-alert** [comment]
Submitted a CR that allows editing volunteer type - I want an OK on the style of implementation before moving forward with the rest of the fields.

Thing is, it seems sensical to me that we shouldn't have to manually create an HTML snippet, a url and a view function for each such field - I'm looking for a way to generate these automatically, but aren't feeling confident enough with Django forms to try this...

**Comment by stavlocker** [comment]
This is already merged, closing
