### ISSUE TITLE
Make organization field in volunteer sign up optional

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#90]

**Comment by flight-alert** [comment]
Are you sure this isn't already optional? it is marked as optional in the code and I remember creating a volunteer without it in production (don't want to create another one to avoid creating more false accounts)

**Comment by stavlocker** [comment]
I tried to create a volunteer without an organization in development, and it seems to work just fine.

**Comment by astar26** [comment]
It's optional right now, closing.
