### ISSUE TITLE
Excel Export Issues

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#92]
Volunteer export - add organization column.
Request export - missing field header, columns misaligned.

**Comment by stavlocker** [comment]
* Which fields are supposed to be included? There are currently some fields that aren't included in the spreadsheet
* What are the Hebrew terms for the "guiding" and "keep_mandatory_worker_children" fields?

@itay-sho

**Comment by astar26** [comment]
remove full name, add organization, languages, neighborhood, address, keep children, hearing way.

Also add creation timestamps (for both volunteers and requests), database id, address (for requests).

**Comment by stavlocker** [comment]
> Also add creation timestamps (for both volunteers and requests), database id, _address (for requests)._
You mentioned address twice. What do you mean by "for requests"?
Also should I also add moving_way? I feel like I should.

**Comment by astar26** [comment]
There are two excel exports - for volunteers and for requests. Both need modification. Volunteers have addresses, and also people in need of help, hence writing them twice (and the clarification).

As for moving way - good idea.

**Comment by stavlocker** [comment]
Ohh, I thought you meant requests as in HttpRequests 😅 
Sure.
What about the type_text (the actual content of the helprequest) in the HelpRequest exporting?
_Soon we'll have a chat platform and all these conversations will be there instead of here lmao_
